services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/userdb
    restart: always

  task-service:
    build: ./task-service
    container_name: task-service

    ports:
      - "3002:3002"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/tasks
    restart: always

  comment-service:
    build: ./comment-service
    container_name: comment-service
    ports:
      - "3003:3003"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/comments
    restart: always

  frontend:
    image: nginx:alpine
    container_name: frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"
