# certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: inam-project-cert
  namespace: project
spec:
  secretName: myapp-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: inam.project.com
  dnsNames:
    - inam.project.com
