name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [user-service, task-service, comment-service, frontend]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: docker.io/${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Decode Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > $HOME/.kube/config

      - name: Apply Kubernetes YAMLs
        run: |
          kubectl apply -f kubernetes/namespace.yaml
          kubectl apply -f kubernetes/mongo-configmap.yaml
          kubectl apply -f kubernetes/mongo-deployment.yaml
          kubectl apply -f kubernetes/user-service.yaml
          kubectl apply -f kubernetes/task-service.yaml
          kubectl apply -f kubernetes/comment-service.yaml
          kubectl apply -f kubernetes/frontend.yaml
          kubectl apply -f kubernetes/ingress.yaml

  terraform:
    name: Apply Terraform Infrastructure
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init & Apply
        working-directory: ./terraform
        run: |
          terraform init
          terraform validate
          terraform apply -auto-approve
